---
title: "NIMBLE Alaska ASA Workshop Overview"
author: "NIMBLE Development Team"
date: "June 2026"
format:
  html:
    toc: true
    toc-location: right
---

# Workshop preparation

To prepare for the workshop:

 - Install NIMBLE (see below)
 - Install additional packages (see below)
 - Download these materials (and check back before the workshop on Monday for updates)

## Help with NIMBLE

Our user manual is [here](https://r-nimble.org/html_manual/cha-welcome-nimble.html).

We have a 'cheatsheet' and a guide to converting from JAGS or WinBUGS to NIMBLE [here](https://r-nimble.org/documentation).

For the small number of you who are not already familiar with writing models in WinBUGS, JAGS, or NIMBLE, you may want to look through the first module (Introduction to NIMBLE) or Section 5.2 of our user manual in advance.

We're happy to answer questions about writing models as we proceed through the workshop, but if you have no experience with it, reviewing in advance will greatly lessen the odds you feel lost right at the beginning.

## Installing NIMBLE

NIMBLE is an R package on CRAN, so in general it will be straightforward to install as with any R package, but you do need a compiler and related tools on your system.  

In summary, here are the steps.

1. Install compiler tools on your system. [https://r-nimble.org/download](https://r-nimble.org/download) has more details on how to install *Rtools* on Windows and how to install the command line tools of *Xcode* on a Mac. Note that if you have packages requiring a compiler (e.g., *Rcpp*) on your computer, you should already have the compiler tools installed.

2. Install the *nimble* package from CRAN in the usual fashion for an R package. More details (including troubleshooting tips) can also be found in Section 4 of the [NIMBLE manual](https://r-nimble.org/html_manual/cha-installing-nimble.html).

3) To test that things are working please run the following code in R:

```
library(nimble)
code <- nimbleCode({
  y ~ dnorm(0,1)
})
model <- nimbleModel(code)
cModel <- compileNimble(model)
```


If that runs without error, you're all set. If not, please see the troubleshooting tips and email nimble.stats@gmail.com directly if you can't get things going.  

In general we encourage you to update to the most recent version of NIMBLE (>=1.4.0).


## Installing additional packages

Some of the packages we will use (beyond those automatically installed with `nimble`) can be installed as follows:

```
install.packages(c("compareMCMCs", "mcmcplots", "CARBayesdata", "sp", "spdep", "classInt", "coda", "nimbleEcology", "nimbleSCR"))
```


# Schedule

Time: 9 am - 4:30 pm Alaska time (GMT-9)


Day 1 (Tuesday June 16):

1. (9 am - 9:45 am) Introduction to NIMBLE: Basic concepts and workflows
2. (10 am - 11 am) Working with NIMBLE models and converting from WinBUGS/JAGS
3. (11:15 am - 12:30 pm) Comparing and customizing MCMC methods in NIMBLE
4. (12:30 pm - 1:30 pm) Lunch (provided)
5. (1:30 pm - 2:30 pm) Strategies for improving MCMC
6. (2:45 pm - 4 pm) Spatial modeling
9. (4:15 pm - 4:30 pm) Writing your own functions and distributions 

Day 2 (Wednesday June 17):

9. (9 am - 10 am) Writing your own functions and distributions (cont'd)
8. (10:15 am - 12 pm) Ecological models (including Hidden Markov Models)
10. (12 pm - 1 pm) Lunch (provided)
11. (1 pm - 2 pm) Introduction to nimbleFunctions and nimble programming
12. (2:15 pm - 3:15 pm) nimbleFunction programming (with user-defined sampler example)
13. (3:30 pm - 4:15 pm) Automatic differentiation, Laplace approximation, and INLA-like nested approximation
14. (4:15 pm - 4:30 pm) Wrapup and NIMBLE 2.0


# A few administrative things

## Where to find stuff

The GitHub site ([https://github.com/nimble-training/nimble-alaska-2026](https://github.com/nimble-training/nimble-alaska-2026)) is the main repository for materials for the modules; you can also get the individual files from GitHub. 

If you're not familiar with Git, you can get these materials by simply going to [https://github.com/nimble-training/nimble-alaska-2026](https://github.com/nimble-training/nimble-alaska-2026) and click on the 'Download ZIP' button in the right side of the window or simply click [here](https://github.com/nimble-training/nimble-alaska-2026/archive/refs/heads/main.zip). See also slide 6 in this document for how to get them using Git or from within RStudio.


## Asking questions and making comments

Please ask questions and make comments as we go through the material.

# Suggestions on how to get the most out of the workshop

We encourage you to:

- try out the code as we walk through it
-  keep your eyes open! -- We'll illustrate a lot of syntax and concepts by example
- try to guess what the syntax means in cases we haven't yet seen that syntax
- play with it and try variations and try to break it and see what happens
- ask questions!


# RStudio and R Markdown

We'll present most of the material from within RStudio, using R Markdown documents with embedded R code. R Markdown is an extension to the Markdown markup language that makes it easy to write HTML in a simple plain text format.  This allows us to both run the R/NIMBLE code directly as well as compile on-the-fly to an HTML file that can be used for presentation. 

Note: The files named *foo.html* have individual slides, while the files named *foo_alt.html* have the same content but all on one page.

Warning: in some cases the processing of the R code in the R Markdown is screwy and the slides have error messages that do not occur if you just run the code directly in R or RStudio. 

# Getting the workshop materials

To download the files, you can do any of the following. 

## From a browser

Simply go to [https://github.com/nimble-training/nimble-alaska-2026](https://github.com/nimble-training/nimble-alaska-2026) and click on the 'Download ZIP' button in the right side of the window or simply click [here](https://github.com/nimble-training/nimble-alaska-2026/archive/refs/heads/main.zip).

## Within RStudio

Within RStudio go to File->New Project->Version Control->Git and enter:

- "Repository URL": https://github.com/nimble-training/nimble-alaska-2026
- "Project Directory Name": nimble-alaska-2026 (or something else of your choosing)
- "Directory": ~/Desktop (or somewhere of your choosing)

Then to update from the repository to get any changes we've made, you can select (from within RStudio):
Tools->Version Control->Pull Branches

or from the Environment/History/Git window, click on the Git tab and then on the blue down arrow.

Be warned that you probably do not want to make your own notes or changes to the files we are providing. Because if you do, and you then do a "Git Pull" to update the materials, you'll have to deal with the conflict between your local version and our version. You probably will want to make a personal copy of such files in another directory or by making copies of files with new names.

## From a terminal window

Run the following commands:

- `cd /directory/where/you/want/repository/located`
- `git clone https://github.com/nimble-training/nimble-alaska-2026`

Then to update from the repository to get any changes we've made:

- `cd /directory/where/you/put/the/repository/nimble-alaska-2026`
- `git pull`

# Installing NIMBLE

NIMBLE is on CRAN, so in general it will be straightforward to install, but you do need a compiler and related tools on your system.  

In summary, here are the steps.

1. Install compiler tools on your system. [https://r-nimble.org/download](https://r-nimble.org/download) has more details on how to install *Rtools* on Windows and how to install the
command line tools of *Xcode* on a Mac.
2. Install the *nimble* package from CRAN.
3. Also install the `nimbleHMC` package from CRAN.

More details can also be found in Section 4 of the [NIMBLE manual](https://r-nimble.org/html_manual/cha-installing-nimble.html).

# The Legal Stuff

- This material was created by the NIMBLE development team and is licensed under a Creative Commons Attribution 3.0 Unported License. You are free to use, modify, and redistribute any of this material with attribution.

- NIMBLE is/has been supported by NSF grants DBI-1147230, ACI-1550488, and DMS-1622444, with additional support provided by postdoctoral funding for D. Turek from the Berkeley Institute for Data Science and Google Summer of Code fellowships for N. Michaud (2015) and C. Lewis-Beck (2017).

